version: '3'
services:
  mongodb:
    image: bitnami/mongodb:4.4
    ports:
      - '27017:27017'
    environment:
      - MONGODB_ROOT_PASSWORD=password
      - MONGODB_USERNAME=code
      - MONGODB_PASSWORD=password
      - MONGODB_DATABASE=code
